# Generated by Django 4.0.3 on 2022-03-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
