# Generated by Django 4.0.3 on 2022-03-13 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_cart_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
