# Generated by Django 4.0.3 on 2022-03-14 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_rename_user_id_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='user_id',
        ),
    ]
