# Generated by Django 4.0.3 on 2022-03-15 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_rename_user_cart_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
