# Generated by Django 4.0.3 on 2022-04-12 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_order_product_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='product',
        ),
    ]
