# Generated by Django 4.0.3 on 2022-04-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date']},
        ),
    ]
